[package]
name = "junkpile_16_wgpu_audio_reactive_spectrum"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "=2.6.3", features = [] }

[dependencies]
bytemuck = { version = "1.24", features = ["derive", "min_const_generics"] }
cpal = "=0.15.3"
pollster = "0.4"
rustfft = "=6.4.1"
serde = { version = "1", features = ["derive"] }
tauri = { version = "=2.11.5", features = ["unstable"] }

[target.'cfg(target_os = "macos")'.dependencies]
wgpu = { version = "=29.0.4", features = ["vulkan-portability"] }

[target.'cfg(not(target_os = "macos"))'.dependencies]
wgpu = "=29.0.4"

[workspace]
