const invoke = window.__TAURI__.core.invoke;
const byId = (id) => document.getElementById(id);
let paused = false;
const DEFAULTS = {render_scale:1,retention:.992,diffusion:.12,erosion:.08,injection:1.2,advection:.75,swirl:1.1,simulation_speed:1,density:2.2,ray_steps:160,exposure:1.05,bloom:.48,fog:.055,threshold:.1,hue_shift:.4,camera_yaw:28,camera_pitch:12,camera_distance:3.25,camera_fov:52,auto_orbit:2,slice_depth:.5,slice_thickness:.04};
function status(message,error=false){byId("status").textContent=message;byId("status").classList.toggle("error",error);byId("error").textContent=error?message:"";}
async function call(command,args={}){try{const value=await invoke(command,args);status("Renderer connected");return value;}catch(error){status(String(error),true);throw error;}}
function formatControl(input){const value=Number(input.value);if(input.dataset.format==="percent")return `${Math.round(value*100)}%`;return value.toFixed(Number(input.dataset.decimals??2));}
function number(value,digits=1){return Number(value??0).toLocaleString(undefined,{maximumFractionDigits:digits});}
function updateInfo(info){const values={backend:info.backend,adapter:info.adapter,volumeResolution:`${info.volumeSize}³`,performance:`${number(info.fps,1)} FPS · ${number(info.frameTimeMs,2)} ms`,sceneName:info.sceneName,viewName:info.viewName,voxelCount:number(info.voxelCount,0),volumeMemory:`${number(info.volumeMemoryMegabytes,1)} MiB`,outputMemory:`${number(info.outputMemoryMegabytes,1)} MiB`,totalMemory:`${number(info.estimatedTotalMegabytes,1)} MiB`,dispatch:`${info.workgroupsPerAxis}³ workgroups`,voxelRate:`${number(info.voxelUpdatesPerSecond/1e9,2)} Gvox/s`,max3d:`${info.maxTextureDimension3d}³`,outputResolution:`${info.outputWidth} × ${info.outputHeight}`};for(const [id,value] of Object.entries(values)){const node=byId(id);if(node)node.textContent=value;}
 document.querySelectorAll('[data-volume-size]').forEach(b=>b.classList.toggle('active',Number(b.dataset.volumeSize)===Number(info.volumeSize)));document.querySelectorAll('[data-resolution]').forEach(b=>b.classList.toggle('active',b.dataset.resolution===info.resolutionPreset));document.querySelectorAll('[data-scene]').forEach(b=>b.classList.toggle('active',Number(b.dataset.scene)===Number(info.scene)));document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',Number(b.dataset.view)===Number(info.viewMode)));paused=Boolean(info.paused);byId('paused').textContent=paused?'Resume':'Pause';byId('paused').classList.toggle('active',paused);byId('burst').classList.toggle('active',Boolean(info.burstActive));if(info.lastError)status(info.lastError,true);}
async function poll(){try{updateInfo(await call('get_renderer_info'));}catch{}}
for(const input of document.querySelectorAll('[data-param]')){const output=input.nextElementSibling;output.value=formatControl(input);input.addEventListener('input',()=>{output.value=formatControl(input);call('set_param',{name:input.dataset.param,value:Number(input.value)});});}
document.querySelectorAll('[data-volume-size]').forEach(b=>b.addEventListener('click',()=>call('set_volume_size',{size:Number(b.dataset.volumeSize)})));
document.querySelectorAll('[data-resolution]').forEach(b=>b.addEventListener('click',()=>call('set_resolution_preset',{preset:b.dataset.resolution})));
document.querySelectorAll('[data-scene]').forEach(b=>b.addEventListener('click',()=>call('set_scene',{scene:Number(b.dataset.scene)})));
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>call('set_view_mode',{mode:Number(b.dataset.view)})));
byId('burst').addEventListener('click',()=>call('trigger_burst'));byId('paused').addEventListener('click',async()=>{paused=!paused;await call('set_paused',{paused});});byId('clearVolume').addEventListener('click',()=>call('clear_volume'));byId('fullscreen').addEventListener('click',()=>call('toggle_renderer_fullscreen'));
byId('resetParams').addEventListener('click',async()=>{await call('reset_params');for(const [id,value] of Object.entries(DEFAULTS)){const input=byId(id);input.value=value;input.nextElementSibling.value=formatControl(input);}paused=false;});poll();setInterval(poll,750);
