'use strict';
const tauri=window.__TAURI__; if(!tauri?.core?.invoke||!tauri?.event?.listen) throw new Error('Tauri v2 global API unavailable');
const {invoke}=tauri.core,{listen}=tauri.event,$=id=>document.getElementById(id),clamp=(v,a,b)=>Math.min(b,Math.max(a,v));
const PARAMS={hue:{label:'Hue',min:0,max:360,step:1,value:188,cc:1,d:0},zoom:{label:'Zoom',min:.4,max:4.5,step:.01,value:1.35,cc:2,d:2},speed:{label:'Speed',min:0,max:2.5,step:.01,value:.55,cc:3,d:2},brightness:{label:'Brightness',min:0,max:2.2,step:.01,value:1.1,cc:7,d:2},distortion:{label:'Distortion',min:0,max:1.2,step:.01,value:.35,cc:10,d:2},complexity:{label:'Complexity',min:1,max:8,step:1,value:5,cc:74,d:0}};
const DEFAULTS=Object.fromEntries(Object.entries(PARAMS).map(([k,s])=>[s.cc,k])); let ccMap=JSON.parse(localStorage.getItem('junkpile-v2-midi-map')||'null')||{...DEFAULTS},learnTarget=null,noteFlash=0,pitchBend=0,eventCount=0,logs=[];
function ccFor(k){const e=Object.entries(ccMap).find(([,v])=>v===k);return e?Number(e[0]):null} function fmt(k,v){return Number(v).toFixed(PARAMS[k].d)}
function buildControls(){const list=$('parameter-list'),learn=$('learn-param');list.innerHTML='';learn.innerHTML='';for(const[k,s]of Object.entries(PARAMS)){learn.insertAdjacentHTML('beforeend',`<option value="${k}">${s.label}</option>`);const row=document.createElement('div');row.className='parameter-row';row.innerHTML=`<div class="parameter-header"><span class="parameter-name">${s.label}</span><span id="${k}-map" class="parameter-map">CC ${ccFor(k)??'—'}</span><output id="${k}-out" class="parameter-value">${fmt(k,s.value)}</output></div><input id="${k}" type="range" min="${s.min}" max="${s.max}" step="${s.step}" value="${s.value}">`;list.append(row);$(k).addEventListener('input',()=>{s.value=+$(k).value;$(`${k}-out`).textContent=fmt(k,s.value);$('midi-overlay').classList.add('hidden')})}}
function refreshMap(){for(const k of Object.keys(PARAMS))$(`${k}-map`).textContent=`CC ${ccFor(k)??'—'}`}
function setParam(k,n){const s=PARAMS[k];if(!s)return;const v=clamp(Math.round((s.min+n*(s.max-s.min))/s.step)*s.step,s.min,s.max);s.value=v;$(k).value=v;$(`${k}-out`).textContent=fmt(k,v)}
function status(cls,text){$('connection-pill').className=`status-pill ${cls}`;$('connection-pill').textContent=text}
function log(kind,text,raw='',error=false){const time=new Date().toLocaleTimeString([],{hour12:false});logs.unshift({time,kind,text,raw,error});logs=logs.slice(0,80);$('midi-log').innerHTML=logs.map(l=>`<div class="log-line ${l.error?'log-error':''}"><span class="log-time">${l.time}</span><span class="log-kind">${l.kind}</span><span class="log-raw">${escapeHtml(l.text)}${l.raw?' · ['+escapeHtml(l.raw)+']':''}</span></div>`).join('')}
function escapeHtml(v){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
async function refresh(){const s=$('port-select'),prior=s.value;s.innerHTML='<option>Scanning…</option>';try{const ports=await invoke('list_midi_ports');s.innerHTML=ports.length?ports.map(n=>`<option>${escapeHtml(n)}</option>`).join(''):'<option value="">— no MIDI inputs found —</option>';if(ports.includes(prior))s.value=prior;log('system',`Found ${ports.length} input port(s)`)}catch(e){status('error','scan error');log('error',String(e),'',true)}}
async function connect(){if(!$('port-select').value)return log('system','Select a MIDI input first');status('loading','connecting');try{const n=await invoke('connect_midi_port_by_name',{portName:$('port-select').value});status('connected','connected');log('system',`Connected to ${n}`)}catch(e){status('error','connect error');log('error',String(e),'',true)}}
async function disconnect(){await invoke('disconnect_midi');status('','disconnected');log('system','Disconnected')}
function describe(e){if(e.kind==='cc')return `Ch ${e.channel} · CC ${e.data1} = ${e.data2}`;if(e.kind==='note_on')return `Ch ${e.channel} · note ${e.data1} on · velocity ${e.data2}`;if(e.kind==='note_off')return `Ch ${e.channel} · note ${e.data1} off`;if(e.kind==='pitch_bend')return `Ch ${e.channel} · pitch bend ${e.pitchBend}`;return `Ch ${e.channel} · ${e.kind}`}
function handle(e){eventCount++;$('message-count').textContent=`${eventCount} events`;$('last-message').textContent=describe(e);$('midi-overlay').classList.add('hidden');if(e.kind==='cc'){if(learnTarget){for(const[c,p]of Object.entries(ccMap))if(p===learnTarget)delete ccMap[c];delete ccMap[e.data1];ccMap[e.data1]=learnTarget;localStorage.setItem('junkpile-v2-midi-map',JSON.stringify(ccMap));log('learn',`Mapped CC ${e.data1} → ${PARAMS[learnTarget].label}`);learnTarget=null;$('learn-pill').className='status-pill';$('learn-pill').textContent='off';$('learn-btn').textContent='Arm learn';refreshMap()}const p=ccMap[e.data1];if(p)setParam(p,e.value);$('cc-value').textContent=`CC${e.data1} · ${e.data2}`;$('cc-meter').style.width=`${e.value*100}%`}else if(e.kind==='note_on'){noteFlash=Math.max(noteFlash,e.value);$('note-value').textContent=e.data2;$('note-meter').style.width=`${e.value*100}%`}else if(e.kind==='pitch_bend'){pitchBend=e.value;$('bend-value').textContent=e.pitchBend;$('bend-meter').style.width=`${Math.abs(e.value)*100}%`}log(e.kind,describe(e),e.raw.join(', '))}
$('refresh-btn').onclick=refresh;$('connect-btn').onclick=connect;$('disconnect-btn').onclick=disconnect;$('debug-btn').onclick=async()=>log('debug',(await invoke('debug_midi_ports')).replaceAll('\n',' / '));$('learn-btn').onclick=()=>{learnTarget=learnTarget?null:$('learn-param').value;$('learn-pill').className=`status-pill ${learnTarget?'armed':''}`;$('learn-pill').textContent=learnTarget?`waiting · ${PARAMS[learnTarget].label}`:'off';$('learn-btn').textContent=learnTarget?'Cancel learn':'Arm learn'};$('reset-map-btn').onclick=()=>{ccMap={...DEFAULTS};localStorage.setItem('junkpile-v2-midi-map',JSON.stringify(ccMap));refreshMap();log('system','Restored default CC map')};
function resetVisual(){for(const[k,s]of Object.entries(PARAMS)){const original={hue:188,zoom:1.35,speed:.55,brightness:1.1,distortion:.35,complexity:5}[k];s.value=original;$(k).value=original;$(`${k}-out`).textContent=fmt(k,original)}noteFlash=0;pitchBend=0}$('reset-btn').onclick=resetVisual;$('fullscreen-btn').onclick=()=>invoke('toggle_fullscreen');document.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='r')resetVisual();if(e.key.toLowerCase()==='f')invoke('toggle_fullscreen')});
const canvas=$('gl-canvas'),gl=canvas.getContext('webgl',{alpha:false,antialias:false,powerPreference:'high-performance'});if(!gl)throw new Error('WebGL unavailable');
const VS=`attribute vec2 a_position;varying vec2 v_uv;void main(){v_uv=a_position*.5+.5;gl_Position=vec4(a_position,0.,1.);}`;
const FS=`precision highp float;varying vec2 v_uv;uniform vec2 u_resolution;uniform float u_time,u_hue,u_zoom,u_brightness,u_distortion,u_complexity,u_note_flash,u_pitch_bend;float h(vec2 p){p=fract(p*vec2(123.34,456.21));p+=dot(p,p+45.32);return fract(p.x*p.y);}float n(vec2 p){vec2 i=floor(p),f=fract(p),u=f*f*(3.-2.*f);return mix(mix(h(i),h(i+vec2(1,0)),u.x),mix(h(i+vec2(0,1)),h(i+vec2(1)),u.x),u.y);}float fbm(vec2 p){float s=0.,a=.5;for(int i=0;i<8;i++){if(float(i)>=u_complexity)break;s+=n(p)*a;p=p*2.03+vec2(17.1,9.2);a*=.5;}return s;}vec3 pal(float t){return .55+.45*cos(6.28318*(t+vec3(0.,.33,.67)));}void main(){vec2 p=(v_uv-.5)*u_zoom;p.x*=u_resolution.x/max(u_resolution.y,1.);float a=u_pitch_bend*.35;mat2 r=mat2(cos(a),-sin(a),sin(a),cos(a));p=r*p;float t=u_time;vec2 q=vec2(fbm(p+vec2(0,t*.08)),fbm(p+vec2(5.2,-t*.06)));float f=fbm(p+q*u_distortion*3.);vec3 c=pal(f+u_hue/360.+t*.025);c*=u_brightness*(.55+f*.8+u_note_flash*.8);gl_FragColor=vec4(c,1.);}`;
function shader(type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s));return s}const prog=gl.createProgram();gl.attachShader(prog,shader(gl.VERTEX_SHADER,VS));gl.attachShader(prog,shader(gl.FRAGMENT_SHADER,FS));gl.linkProgram(prog);if(!gl.getProgramParameter(prog,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(prog));const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,1,1]),gl.STATIC_DRAW);const a=gl.getAttribLocation(prog,'a_position');gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,2,gl.FLOAT,false,0,0);const U=Object.fromEntries(['u_resolution','u_time','u_hue','u_zoom','u_brightness','u_distortion','u_complexity','u_note_flash','u_pitch_bend'].map(n=>[n,gl.getUniformLocation(prog,n)]));let t=0,last=performance.now();function frame(now){const rect=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2),w=Math.max(1,Math.floor(rect.width*d)),h=Math.max(1,Math.floor(rect.height*d));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;$('renderer-info').textContent=`${w}×${h} · ${gl.getParameter(gl.RENDERER)}`}gl.viewport(0,0,w,h);t+=(now-last)/1000*PARAMS.speed.value;last=now;gl.useProgram(prog);gl.uniform2f(U.u_resolution,w,h);gl.uniform1f(U.u_time,t);for(const k of ['hue','zoom','brightness','distortion','complexity'])gl.uniform1f(U[`u_${k}`],PARAMS[k].value);gl.uniform1f(U.u_note_flash,noteFlash);gl.uniform1f(U.u_pitch_bend,pitchBend);gl.drawArrays(gl.TRIANGLE_STRIP,0,4);noteFlash*=.93;requestAnimationFrame(frame)}
buildControls();refresh();listen('midi-event',e=>handle(e.payload));requestAnimationFrame(frame);
