[package]
name = "junkpile_07_wgpu_high_resolution_lab"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "=2.6.3", features = [] }

[dependencies]
bytemuck = { version = "1.24", features = ["derive"] }
pollster = "0.4"
serde = { version = "1", features = ["derive"] }
tauri = { version = "=2.11.5", features = ["unstable"] }
wgpu = "=29.0.4"

[workspace]
