[package]
name = "junkpile_17_tauri_v1_glsl_shader_playground"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1", features = [ "fs-write-file", "dialog-save", "wry"] }

[features]
default = []
custom-protocol = ["tauri/custom-protocol"]

[workspace]
resolver = "2"
