[package]
name = "junkpile_10_tauri_v2_midi_input"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
midir = "0.10"
serde = { version = "1", features = ["derive"] }

[workspace]
resolver = "2"
