[package]
name = "junkpile_22_tauri_v1_image_sequence_player"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1", features = [ "protocol-asset", "fs-write-file", "dialog-open", "window-all", "dialog-save", "wry"] }

[features]
default = []
custom-protocol = ["tauri/custom-protocol"]

# Keep this standalone example isolated from any Cargo workspace above it.
[workspace]
resolver = "2"
