[package]
name = "webcam-tauri-v2-single-template"
version = "0.2.0"
description = "Junkpile Example 06 — Webcam Texture Single Window"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

[workspace]
resolver = "2"
